active_modules:
  ocpp:
    module: OCPP
    config_module:
      ChargePointConfigPath: /mnt/user_data/user-config/ocpp/ocpp-config.json
      UserConfigPath: /mnt/user_data/user-config/ocpp/user-config.json
      DatabasePath: /mnt/user_data/user-config/ocpp
    connections:
      evse_manager:
        - module_id: evse_manager
          implementation_id: evse
      reservation:
        - module_id: auth
          implementation_id: reservation
      auth:
        - module_id: auth
          implementation_id: main
      system:
        - module_id: system
          implementation_id: main
  system:
    module: System
  auth:
    module: Auth
    config_module:
      connection_timeout: 30
      selection_algorithm: PlugEvents
    connections:
      token_provider:
      - module_id: ocpp
        implementation_id: auth_provider
      - module_id: token_provider_rfid
        implementation_id: main
      token_validator:
      - module_id: ocpp
        implementation_id: auth_validator
      evse_manager:
      - module_id: evse_manager
        implementation_id: evse
  token_provider_1: null
  token_validator: null
